trunk/urls.py
from django.conf.urls import patterns, url
#from django.contrib import admin

import file.views

urlpatterns = [
    # Examples:
    # url(r'^$', 'approve_me_please.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
    url(r'^$', file.views.home, name='home'),

    url(r'^add/$', file.views.upload),
    url(r'^(?P<permalink>[a-zA-Z0-9]{1,10})/$', file.views.file_view),
]

trunk/file/models.py
from django.db import models

class File(models.Model):
    permalink = models.SlugField(u'Permalink', max_length=10, db_index=True)
    width = models.IntegerField(u'Width')
    height = models.IntegerField(u'Height')
    filetype = models.CharField(u'Filetype', max_length=4)
    filename = models.CharField(u'Filename', max_length=16)
    file_size = models.FloatField(u'File Size')
    added = models.DateTimeField(u'Added', auto_now_add=True)
    comment = models.TextField(u'Comment')
    
    #def __unicode__(self):
    #    return self.title
        
    @models.permalink
    def get_absolute_url(self):
        return ('file.views.view_file', (), {'permalink': self.permalink,})

trunk/file/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import File

class FileUploadForm(forms.Form):
    file_file = forms.FileField(label=u'File', required=True, error_messages={'required': 'Select File'})
    width = forms.CharField(label=u'Width', min_length=2, max_length=4, error_messages={'required': 'Enter Width'})
    height = forms.CharField(label=u'Height', min_length=2, max_length=4, error_messages={'required': 'Enter Height'}) 
    comment = forms.CharField(label=u'Comment', required = False, max_length=300)

trunk/file/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404

from django.http import HttpResponse

from django.contrib import messages

from django.template import RequestContext

from trunk.settings import SITEHOST, MEDIA_TEMP_DIRECTORY, MEDIA_UPLOADS_DIRECTORY
from models import File
from forms import FileUploadForm


import os
import shutil
import random
import string

def home(request):
    context = {}
    return render(request, 'home.html', context)

def file_view(request, permalink):

    entries_all = File.objects.all()[:20]
    # print all_entries.len()
    count = len(entries_all)
    if count > 200:
        entries = File.objects.all()[:1]

        for f in entries:
            # delete_file(a)
            # print a.permalink
            filename = '%s.%s' % (f.permalink, f.filetype)
            delete_file(MEDIA_UPLOADS_DIRECTORY + filename)
            f.delete()
            #messages.success(request, u'File deleted %s' % filename) 
            # print len(entries)


    file = get_object_or_404(File, permalink__exact = permalink)
    return render(request, 'file/view.html', {'file': file})

def upload(request):
    ALLOWED_FILE_TYPES = ['application/x-shockwave-flash', 'image/jpeg', 'image/gif']
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            content_type = request.FILES['file_file'].content_type
            if content_type in ALLOWED_FILE_TYPES:
                if request.FILES.get('file_file',''):            
                    destination_path = '%s%s' % (MEDIA_TEMP_DIRECTORY, make_random_string(12))
                    if not handle_uploaded_file(request.FILES['file_file'], destination_path):
                        messages.error(request, u'15Mb max ;(')
                        # template_data = RequestContext(request, {'form': form})
                        return render(request, 'banner/upload.html', {'form': form})

                    # ALLOWED_FILE_TYPES = ['application/x-shockwave-flash', 'image/jpeg', 'image/gif']

                    # file_type = file.content_type.split('/')[0]
                    if content_type == 'application/x-shockwave-flash': filetype = 'swf'
                    if content_type == 'image/jpeg': filetype = 'jpeg'
                    if content_type == 'image/gif': filetype = 'gif'

                    f = File(filename = '0')
                    f.filetype = filetype
                    f.width = form.cleaned_data['width']
                    f.height = form.cleaned_data['height']
                    f.comment = form.cleaned_data['comment']
                    f.file_size = request.FILES['file_file'].size
                    f.save()
                        
                    f.permalink = make_key(f.id)
                    f.save()

                    filename = '%s.%s' % (f.permalink, f.filetype)
                    shutil.move(destination_path, MEDIA_UPLOADS_DIRECTORY + filename)
                    f.save()

                    messages.success(request, u'File uploaded')            
                    return redirect('%s/%s/' % (SITEHOST, f.permalink))

                else:
                    messages.error(request, u'Something wrong')
                    return render(request, 'file/upload.html', {'form': form})
            else:
                messages.error(request, u'File type is not supported')
                return render(request, 'file/upload.html', {'form': form})
        else:
            messages.error(request, u'No File ;(')
            return render(request, 'file/upload.html', {'form': form})
    else:
        form = FileUploadForm(initial = {'width': '240', 'height': '400',}) 
        return render(request, 'file/upload.html', {'form': form})

def make_key(num):
    characters = string.digits + string.ascii_lowercase
    base = len(characters)
    rem, res = divmod(num, base);
    return ('' if rem == 0 else make_key(rem)) + characters[res]


def handle_uploaded_file(f, path):
    destination = open(path, 'wb+')
    for chunk in f.chunks():
        destination.write(chunk)
    destination.close()
    return True
    
def make_random_string(ln):
    return ''.join( [random.choice(string.letters) for i in xrange(ln)] )

def check_dir(dir):
    if not os.path.isdir(dir):
        os.mkdir(dir)
        
def delete_file(path):
    if os.path.isfile(path):
        os.remove(path)

def remove_directory(dir):
    if os.path.isdir(dir):
        shutil.rmtree(dir)
        
def check_file_exists(path):
    if os.path.isfile(path):
        return True
    else:
        return False
        
def move_file(src, dst):
    shutil.move(src, dst)
    return

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Approve Me Please</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, minimal-ui">
    
    <link href="{{ MEDIA_URL }}style.css" rel="stylesheet">    
</head>
<body>

    <!-- <div id="debug_field">DEBUG</div> -->

    {% if messages %}<div id="messages"><div id="messages_initial"><ul>{% for message in messages %}<li{% if message.tags %} class="{{ message.tags }}"{% endif %}><div>{{ message }}</div></li>{% endfor %}</ul></div></div>{% endif %}

{% block main %}{% endblock %}

        
    <div id="footer" class="footer">
        <div class="footer__wrap">    
            <div class="copy"><p class="m">/by <a href="http://ress.ws">@ress</a></p></div>        
        </div>
    </div>
    

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<script src="{{ MEDIA_URL }}main.js"></script>

</body>
</html>

templates/file/upload.html
{% extends "base.html" %}

{% block main %}

    <div id="title" class="title">
        <div class="title__wrap">
            <div><a class="leading" href="/">Upload</a></div>
        </div>
    </div>

    <div id="content" class="content">
        <div class="content__wrap">
            <div class="form">
                

                <form enctype="multipart/form-data" method="POST" action="">

                    <div>
                        {{ form.file_file.errors }}
                        <label for="id_file_file">Select File:</label>
                        {{ form.file_file }}
                    </div>
                   

                    <div class="widthheight">
                        {{ form.width.errors }}{{ form.height.errors }}
                        <span><label for="id_width">Width &mdash; </label>{{ form.width }}</span>
                        <span>{{ form.height }}<label for="id_height"> &mdash; Height</label></span>
                    </div>

                    <div class="comment">
                        {{ form.comment.errors }}
                        <label for="id_comment">Comment:</label>
                        <div>{{ form.comment }}</div>
                    </div>

                    <div>                        
                        <input class="button" type="submit" value="OK">
                    </div>                    
                </form>


            </div>
        </div>
    </div>

    <div id="info" class="info">
        <div class="info__wrap">
            
        </div>
    </div>
    


{% endblock %}

templates/file/view.html
{% extends "base.html" %}

{% block main %}

    <div id="title" class="title">
        <div class="title__wrap">
            <div><a class="leading" href="/">Approve Me Please</a></div>
        </div>
    </div>

    <div id="content" class="content">
        <div class="content__wrap">
            {% if file.filetype == "jpeg" %}
                <img src="{{ MEDIA_URL }}uploads/{{ file.permalink }}.{{ file.filetype }}" width="{{ file.width }}" height="{{ file.height }}" border="0" alt="">
            {% endif %}
            {% if file.filetype == "gif" %}
                <img src="{{ MEDIA_URL }}uploads/{{ file.permalink }}.{{ file.filetype }}" width="{{ file.width }}" height="{{ file.height }}" border="0" alt="">
            {% endif %}
            {% if file.filetype == "swf" %}
                
                <!-- <div id="flashContent" style="width: {{ file.width }}px; height: {{ file.height }}px;"> -->
                <div id="flashContent">
                    <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="{{ file.width }}" height="{{ file.height }}" id="id_{{ file.permalink }}" align="middle">
                        <param name="movie" value="{{ MEDIA_URL }}uploads/{{ file.permalink }}.{{ file.filetype }}" />
                        <param name="quality" value="high" />
                        <param name="bgcolor" value="#ffffff" />
                        <param name="play" value="true" />
                        <param name="loop" value="true" />
                        <param name="wmode" value="window" />
                        <param name="scale" value="showall" />
                        <param name="menu" value="true" />
                        <param name="devicefont" value="false" />
                        <param name="salign" value="" />
                        <param name="allowScriptAccess" value="sameDomain" />
                        <!--[if !IE]>-->
                        <object type="application/x-shockwave-flash" data="{{ MEDIA_URL }}uploads/{{ file.permalink }}.{{ file.filetype }}" width="{{ file.width }}" height="{{ file.height }}">
                            <param name="movie" value="{{ MEDIA_URL }}uploads/{{ file.permalink }}.{{ file.filetype }}" />
                            <param name="quality" value="high" />
                            <param name="bgcolor" value="#ffffff" />
                            <param name="play" value="true" />
                            <param name="loop" value="true" />
                            <param name="wmode" value="window" />
                            <param name="scale" value="showall" />
                            <param name="menu" value="true" />
                            <param name="devicefont" value="false" />
                            <param name="salign" value="" />
                            <param name="allowScriptAccess" value="sameDomain" />
                        <!--<![endif]-->
                            <a href="http://www.adobe.com/go/getflash">
                                <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" />
                            </a>
                        <!--[if !IE]>-->
                        </object>
                        <!--<![endif]-->
                    </object>
                </div>

            {% endif %}

        </div>
    </div>

    <div id="info" class="info">
        <div class="info__wrap">
            {% if file.comment %}<div class="comment"><p>{{ file.comment }}</p></div>{% endif %}
            <div class="bottom_line"><p>{{ file.filetype }} / {{ file.width }}x{{ file.height }} / {{ file.file_size|filesizeformat }}</p></div>
            <div><a href="{{ MEDIA_URL }}uploads/{{ file.permalink }}.{{ file.filetype }}">Download</a></div>
        </div>
    </div>


{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block main %}

    <div id="title" class="title">
        <div class="title__wrap">
            <div><a class="leading" href="/">Hello</a></div>
        </div>
    </div>

    <div id="content" class="content">
        <div class="content__wrap">
        </div>
    </div>

    <div id="info" class="info">
        <div class="info__wrap">
            
        </div>
    </div>


{% endblock %}